AWSTemplateFormatVersion: "2010-09-09"
Description: Launch an EC2 instance
Resources:
  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties: 
      InstanceType: "t2.micro"
      ImageId: "ami-04b4f1a9cf54c11d0"